#!/bin/sh
if [ -z "$AGORA_FOUNTAIN_VERSION" ]; then
    /usr/lib/agora/.env/bin/pip install --upgrade Agora-Fountain
else
	/usr/lib/agora/.env/bin/pip install --upgrade Agora-Fountain==$AGORA_FOUNTAIN_VERSION
fi

/usr/lib/agora/.env/bin/fountain &
